version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourSecurePassword123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql

  pckonfiguratorbackend:
    image: pckonfiguratorbackend
    build:
      context: .
      dockerfile: PCKonfiguratorBackend/Dockerfile
    depends_on:
      - mssql
    environment:
      DB_HOST: "mssql"
      DB_PORT: "1433"
      DB_USER: "sa"
      DB_PASSWORD: "YourSecurePassword123!"
      DB_NAME: "PCKonfigurator"
    ports:
      - "8080:8080"

volumes:
  mssql_data:
    driver: local
