version: '3.8'

services:
  pckonfiguratorbackend:
    image: pckonfiguratorbackend
    build:
      context: .
      dockerfile: PCKonfiguratorBackend/Dockerfile
    depends_on:
      - mssql
    networks:
      - pckonfigurator_network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - pckonfigurator_network

networks:
  pckonfigurator_network:
