networks:
  app-network:
    driver: bridge

services:
  pckonfiguratorbackend:
    image: pckonfiguratorbackend
    build:
      context: .
      dockerfile: PCKonfiguratorBackend/Dockerfile
    networks:
      - app-network
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
